[[pages]]
path = "cpapredict.py"
name = "SmartExam Creator"
icon = "ğŸ“"

[[pages]]
path = "pages/History.py"
name = "Chat with PDF"
icon = "ğŸ“„"

[[pages]]
path = "pages/another_page.py"
name = "Chat with Images"
icon = "ğŸ–¼ï¸"


