[[pages]]
path = "cpapredict_ubah_value.py"
name = "SmartExam Creator"
icon = "ğŸ“"

[[pages]]
path = "pages/dataset.py"
name = "Chat with PDF"
icon = "ğŸ“„"

[[pages]]
path = "pages/history.py"
name = "Chat with Images"
icon = "ğŸ–¼ï¸"
